Algoritmo "IDENTIFICAÇÃO POR COR"

Var

valor:real
cor, verde, azul, amarelo, vermelho:caractere

Inicio

escreval("Escreva qual a cor do cd:")
leia(cor)


se (cor="verde") entao
escreval("O valor do produto é: R$10,00")
fimse

se (cor="azul") entao
escreval("O valor do produto é: R$20,00")
fimse

se (cor="amarelo") entao
escreval("O valor do produto é: R$30,00")
fimse

se (cor="vermelho") entao
escreval("O valor do produto é:R$40,00")
fimse

 


Fimalgoritmo
